version: 0.2

phases:
  pre_build:
    commands:
      - pip install --upgrade pip
      - pip install selenium
      - pip install webdriver_manager
  build: 
    commands:
      - python3 conf/projeqtor_post.py
      
    
