version: 0.2

phases:
  pre_build:
    commands:
      - rm /etc/apt/sources.list.d/sbt.list
      - add-apt-repository ppa:mozillateam/firefox-next
      - apt-get update
      - apt-get install firefox xvfb
      - Xvfb :10 -ac &
      - export DISPLAY=:10
      - pip install --upgrade pip
      - pip install selenium
      - pip install webdriver_manager
  build: 
    commands:
      - python3 conf/projeqtor_post.py
      
    
