version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - pip install selenium
      - pip install webdriver_manager
  build: 
    commands:
      - python3 conf/projeqtor_post.py
      
    
